<?php
$Dossier_Classes="codes/classes/";
$Dossier_Controles="codes/controles/";
$Dossier_Fonctions="codes/fonctions/";
$Dossier_Styles="codes/styles/";
$Dossier_Images_Site="fichier/site/image/";
$Dossier_Image_Public="fichier/public/image/";
$Dossier_Image_Public_Miniature="fichier/public/miniature/";
$Dossier_Audio_Public="fichier/public/audio/";
$Dossier_Serveur="codes/serveur/";
?>